### ISSUE TITLE
SubscribeQueue how to catch error

### ISSUE THREAD

**Issue by huangang** [nest-x/nestx-amqp#320]
when SubscribeQueue happen error， there is no place to catch errors

**Comment by aquariuslt** [comment]
currently design or `@SubscribeQueue` catching error, using `exceptionQueue`

you can refer [Consumer & ConsumeQueueOptions.exceptionQueue](https://github.com/nest-x/nestx-amqp/blob/master/src/services/consumer.ts#L30)
